/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmarEmailRouteImport } from './routes/confirmar-email'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedJogoRouteImport } from './routes/_authenticated/jogo'
import { Route as AuthenticatedCriarHeroiRouteImport } from './routes/_authenticated/criar-heroi'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedJogoIndexRouteImport } from './routes/_authenticated/jogo.index'
import { Route as AuthenticatedJogoCarteiraRouteImport } from './routes/_authenticated/jogo.carteira'
import { Route as AuthenticatedJogoArenaRouteImport } from './routes/_authenticated/jogo.arena'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedAdminAdminAuditoriaRouteImport } from './routes/_authenticated/_admin/admin.auditoria'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarEmailRoute = ConfirmarEmailRouteImport.update({
  id: '/confirmar-email',
  path: '/confirmar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJogoRoute = AuthenticatedJogoRouteImport.update({
  id: '/jogo',
  path: '/jogo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriarHeroiRoute = AuthenticatedCriarHeroiRouteImport.update({
  id: '/criar-heroi',
  path: '/criar-heroi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJogoIndexRoute = AuthenticatedJogoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedJogoRoute,
} as any)
const AuthenticatedJogoCarteiraRoute =
  AuthenticatedJogoCarteiraRouteImport.update({
    id: '/carteira',
    path: '/carteira',
    getParentRoute: () => AuthenticatedJogoRoute,
  } as any)
const AuthenticatedJogoArenaRoute = AuthenticatedJogoArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => AuthenticatedJogoRoute,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAdminAuditoriaRoute =
  AuthenticatedAdminAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/termos': typeof TermosRoute
  '/criar-heroi': typeof AuthenticatedCriarHeroiRoute
  '/jogo': typeof AuthenticatedJogoRouteWithChildren
  '/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/jogo/arena': typeof AuthenticatedJogoArenaRoute
  '/jogo/carteira': typeof AuthenticatedJogoCarteiraRoute
  '/jogo/': typeof AuthenticatedJogoIndexRoute
  '/admin/auditoria': typeof AuthenticatedAdminAdminAuditoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/termos': typeof TermosRoute
  '/criar-heroi': typeof AuthenticatedCriarHeroiRoute
  '/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/jogo/arena': typeof AuthenticatedJogoArenaRoute
  '/jogo/carteira': typeof AuthenticatedJogoCarteiraRoute
  '/jogo': typeof AuthenticatedJogoIndexRoute
  '/admin/auditoria': typeof AuthenticatedAdminAdminAuditoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/termos': typeof TermosRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/criar-heroi': typeof AuthenticatedCriarHeroiRoute
  '/_authenticated/jogo': typeof AuthenticatedJogoRouteWithChildren
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/_authenticated/jogo/arena': typeof AuthenticatedJogoArenaRoute
  '/_authenticated/jogo/carteira': typeof AuthenticatedJogoCarteiraRoute
  '/_authenticated/jogo/': typeof AuthenticatedJogoIndexRoute
  '/_authenticated/_admin/admin/auditoria': typeof AuthenticatedAdminAdminAuditoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/confirmar-email'
    | '/login'
    | '/privacidade'
    | '/ranking'
    | '/recuperar-senha'
    | '/reset-password'
    | '/roadmap'
    | '/termos'
    | '/criar-heroi'
    | '/jogo'
    | '/admin'
    | '/jogo/arena'
    | '/jogo/carteira'
    | '/jogo/'
    | '/admin/auditoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/confirmar-email'
    | '/login'
    | '/privacidade'
    | '/ranking'
    | '/recuperar-senha'
    | '/reset-password'
    | '/roadmap'
    | '/termos'
    | '/criar-heroi'
    | '/admin'
    | '/jogo/arena'
    | '/jogo/carteira'
    | '/jogo'
    | '/admin/auditoria'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/confirmar-email'
    | '/login'
    | '/privacidade'
    | '/ranking'
    | '/recuperar-senha'
    | '/reset-password'
    | '/roadmap'
    | '/termos'
    | '/_authenticated/_admin'
    | '/_authenticated/criar-heroi'
    | '/_authenticated/jogo'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/jogo/arena'
    | '/_authenticated/jogo/carteira'
    | '/_authenticated/jogo/'
    | '/_authenticated/_admin/admin/auditoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ConfirmarEmailRoute: typeof ConfirmarEmailRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RankingRoute: typeof RankingRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-email': {
      id: '/confirmar-email'
      path: '/confirmar-email'
      fullPath: '/confirmar-email'
      preLoaderRoute: typeof ConfirmarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jogo': {
      id: '/_authenticated/jogo'
      path: '/jogo'
      fullPath: '/jogo'
      preLoaderRoute: typeof AuthenticatedJogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criar-heroi': {
      id: '/_authenticated/criar-heroi'
      path: '/criar-heroi'
      fullPath: '/criar-heroi'
      preLoaderRoute: typeof AuthenticatedCriarHeroiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jogo/': {
      id: '/_authenticated/jogo/'
      path: '/'
      fullPath: '/jogo/'
      preLoaderRoute: typeof AuthenticatedJogoIndexRouteImport
      parentRoute: typeof AuthenticatedJogoRoute
    }
    '/_authenticated/jogo/carteira': {
      id: '/_authenticated/jogo/carteira'
      path: '/carteira'
      fullPath: '/jogo/carteira'
      preLoaderRoute: typeof AuthenticatedJogoCarteiraRouteImport
      parentRoute: typeof AuthenticatedJogoRoute
    }
    '/_authenticated/jogo/arena': {
      id: '/_authenticated/jogo/arena'
      path: '/arena'
      fullPath: '/jogo/arena'
      preLoaderRoute: typeof AuthenticatedJogoArenaRouteImport
      parentRoute: typeof AuthenticatedJogoRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/auditoria': {
      id: '/_authenticated/_admin/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
  }
}

interface AuthenticatedAdminAdminRouteChildren {
  AuthenticatedAdminAdminAuditoriaRoute: typeof AuthenticatedAdminAdminAuditoriaRoute
}

const AuthenticatedAdminAdminRouteChildren: AuthenticatedAdminAdminRouteChildren =
  {
    AuthenticatedAdminAdminAuditoriaRoute:
      AuthenticatedAdminAdminAuditoriaRoute,
  }

const AuthenticatedAdminAdminRouteWithChildren =
  AuthenticatedAdminAdminRoute._addFileChildren(
    AuthenticatedAdminAdminRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRouteWithChildren
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRouteWithChildren,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedJogoRouteChildren {
  AuthenticatedJogoArenaRoute: typeof AuthenticatedJogoArenaRoute
  AuthenticatedJogoCarteiraRoute: typeof AuthenticatedJogoCarteiraRoute
  AuthenticatedJogoIndexRoute: typeof AuthenticatedJogoIndexRoute
}

const AuthenticatedJogoRouteChildren: AuthenticatedJogoRouteChildren = {
  AuthenticatedJogoArenaRoute: AuthenticatedJogoArenaRoute,
  AuthenticatedJogoCarteiraRoute: AuthenticatedJogoCarteiraRoute,
  AuthenticatedJogoIndexRoute: AuthenticatedJogoIndexRoute,
}

const AuthenticatedJogoRouteWithChildren =
  AuthenticatedJogoRoute._addFileChildren(AuthenticatedJogoRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCriarHeroiRoute: typeof AuthenticatedCriarHeroiRoute
  AuthenticatedJogoRoute: typeof AuthenticatedJogoRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCriarHeroiRoute: AuthenticatedCriarHeroiRoute,
  AuthenticatedJogoRoute: AuthenticatedJogoRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ConfirmarEmailRoute: ConfirmarEmailRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RankingRoute: RankingRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
