/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmarEmailRouteImport } from './routes/confirmar-email'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedJogoRouteImport } from './routes/_authenticated/jogo'
import { Route as AuthenticatedCriarHeroiRouteImport } from './routes/_authenticated/criar-heroi'
import { Route as AuthenticatedJogoIndexRouteImport } from './routes/_authenticated/jogo.index'
import { Route as AuthenticatedJogoSocialRouteImport } from './routes/_authenticated/jogo.social'
import { Route as AuthenticatedJogoPrioridadesRouteImport } from './routes/_authenticated/jogo.prioridades'
import { Route as AuthenticatedJogoMissoesRouteImport } from './routes/_authenticated/jogo.missoes'
import { Route as AuthenticatedJogoLojaRouteImport } from './routes/_authenticated/jogo.loja'
import { Route as AuthenticatedJogoInventarioRouteImport } from './routes/_authenticated/jogo.inventario'
import { Route as AuthenticatedJogoEquipeRouteImport } from './routes/_authenticated/jogo.equipe'
import { Route as AuthenticatedJogoCombateRouteImport } from './routes/_authenticated/jogo.combate'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarEmailRoute = ConfirmarEmailRouteImport.update({
  id: '/confirmar-email',
  path: '/confirmar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJogoRoute = AuthenticatedJogoRouteImport.update({
  id: '/jogo',
  path: '/jogo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriarHeroiRoute = AuthenticatedCriarHeroiRouteImport.update({
  id: '/criar-heroi',
  path: '/criar-heroi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJogoIndexRoute = AuthenticatedJogoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedJogoRoute,
} as any)
const AuthenticatedJogoSocialRoute = AuthenticatedJogoSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedJogoRoute,
} as any)
const AuthenticatedJogoPrioridadesRoute =
  AuthenticatedJogoPrioridadesRouteImport.update({
    id: '/prioridades',
    path: '/prioridades',
    getParentRoute: () => AuthenticatedJogoRoute,
  } as any)
const AuthenticatedJogoMissoesRoute =
  AuthenticatedJogoMissoesRouteImport.update({
    id: '/missoes',
    path: '/missoes',
    getParentRoute: () => AuthenticatedJogoRoute,
  } as any)
const AuthenticatedJogoLojaRoute = AuthenticatedJogoLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedJogoRoute,
} as any)
const AuthenticatedJogoInventarioRoute =
  AuthenticatedJogoInventarioRouteImport.update({
    id: '/inventario',
    path: '/inventario',
    getParentRoute: () => AuthenticatedJogoRoute,
  } as any)
const AuthenticatedJogoEquipeRoute = AuthenticatedJogoEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedJogoRoute,
} as any)
const AuthenticatedJogoCombateRoute =
  AuthenticatedJogoCombateRouteImport.update({
    id: '/combate',
    path: '/combate',
    getParentRoute: () => AuthenticatedJogoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/termos': typeof TermosRoute
  '/criar-heroi': typeof AuthenticatedCriarHeroiRoute
  '/jogo': typeof AuthenticatedJogoRouteWithChildren
  '/jogo/combate': typeof AuthenticatedJogoCombateRoute
  '/jogo/equipe': typeof AuthenticatedJogoEquipeRoute
  '/jogo/inventario': typeof AuthenticatedJogoInventarioRoute
  '/jogo/loja': typeof AuthenticatedJogoLojaRoute
  '/jogo/missoes': typeof AuthenticatedJogoMissoesRoute
  '/jogo/prioridades': typeof AuthenticatedJogoPrioridadesRoute
  '/jogo/social': typeof AuthenticatedJogoSocialRoute
  '/jogo/': typeof AuthenticatedJogoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/termos': typeof TermosRoute
  '/criar-heroi': typeof AuthenticatedCriarHeroiRoute
  '/jogo/combate': typeof AuthenticatedJogoCombateRoute
  '/jogo/equipe': typeof AuthenticatedJogoEquipeRoute
  '/jogo/inventario': typeof AuthenticatedJogoInventarioRoute
  '/jogo/loja': typeof AuthenticatedJogoLojaRoute
  '/jogo/missoes': typeof AuthenticatedJogoMissoesRoute
  '/jogo/prioridades': typeof AuthenticatedJogoPrioridadesRoute
  '/jogo/social': typeof AuthenticatedJogoSocialRoute
  '/jogo': typeof AuthenticatedJogoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/termos': typeof TermosRoute
  '/_authenticated/criar-heroi': typeof AuthenticatedCriarHeroiRoute
  '/_authenticated/jogo': typeof AuthenticatedJogoRouteWithChildren
  '/_authenticated/jogo/combate': typeof AuthenticatedJogoCombateRoute
  '/_authenticated/jogo/equipe': typeof AuthenticatedJogoEquipeRoute
  '/_authenticated/jogo/inventario': typeof AuthenticatedJogoInventarioRoute
  '/_authenticated/jogo/loja': typeof AuthenticatedJogoLojaRoute
  '/_authenticated/jogo/missoes': typeof AuthenticatedJogoMissoesRoute
  '/_authenticated/jogo/prioridades': typeof AuthenticatedJogoPrioridadesRoute
  '/_authenticated/jogo/social': typeof AuthenticatedJogoSocialRoute
  '/_authenticated/jogo/': typeof AuthenticatedJogoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/confirmar-email'
    | '/login'
    | '/privacidade'
    | '/ranking'
    | '/recuperar-senha'
    | '/reset-password'
    | '/roadmap'
    | '/termos'
    | '/criar-heroi'
    | '/jogo'
    | '/jogo/combate'
    | '/jogo/equipe'
    | '/jogo/inventario'
    | '/jogo/loja'
    | '/jogo/missoes'
    | '/jogo/prioridades'
    | '/jogo/social'
    | '/jogo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/confirmar-email'
    | '/login'
    | '/privacidade'
    | '/ranking'
    | '/recuperar-senha'
    | '/reset-password'
    | '/roadmap'
    | '/termos'
    | '/criar-heroi'
    | '/jogo/combate'
    | '/jogo/equipe'
    | '/jogo/inventario'
    | '/jogo/loja'
    | '/jogo/missoes'
    | '/jogo/prioridades'
    | '/jogo/social'
    | '/jogo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/confirmar-email'
    | '/login'
    | '/privacidade'
    | '/ranking'
    | '/recuperar-senha'
    | '/reset-password'
    | '/roadmap'
    | '/termos'
    | '/_authenticated/criar-heroi'
    | '/_authenticated/jogo'
    | '/_authenticated/jogo/combate'
    | '/_authenticated/jogo/equipe'
    | '/_authenticated/jogo/inventario'
    | '/_authenticated/jogo/loja'
    | '/_authenticated/jogo/missoes'
    | '/_authenticated/jogo/prioridades'
    | '/_authenticated/jogo/social'
    | '/_authenticated/jogo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ConfirmarEmailRoute: typeof ConfirmarEmailRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RankingRoute: typeof RankingRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-email': {
      id: '/confirmar-email'
      path: '/confirmar-email'
      fullPath: '/confirmar-email'
      preLoaderRoute: typeof ConfirmarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jogo': {
      id: '/_authenticated/jogo'
      path: '/jogo'
      fullPath: '/jogo'
      preLoaderRoute: typeof AuthenticatedJogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criar-heroi': {
      id: '/_authenticated/criar-heroi'
      path: '/criar-heroi'
      fullPath: '/criar-heroi'
      preLoaderRoute: typeof AuthenticatedCriarHeroiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jogo/': {
      id: '/_authenticated/jogo/'
      path: '/'
      fullPath: '/jogo/'
      preLoaderRoute: typeof AuthenticatedJogoIndexRouteImport
      parentRoute: typeof AuthenticatedJogoRoute
    }
    '/_authenticated/jogo/social': {
      id: '/_authenticated/jogo/social'
      path: '/social'
      fullPath: '/jogo/social'
      preLoaderRoute: typeof AuthenticatedJogoSocialRouteImport
      parentRoute: typeof AuthenticatedJogoRoute
    }
    '/_authenticated/jogo/prioridades': {
      id: '/_authenticated/jogo/prioridades'
      path: '/prioridades'
      fullPath: '/jogo/prioridades'
      preLoaderRoute: typeof AuthenticatedJogoPrioridadesRouteImport
      parentRoute: typeof AuthenticatedJogoRoute
    }
    '/_authenticated/jogo/missoes': {
      id: '/_authenticated/jogo/missoes'
      path: '/missoes'
      fullPath: '/jogo/missoes'
      preLoaderRoute: typeof AuthenticatedJogoMissoesRouteImport
      parentRoute: typeof AuthenticatedJogoRoute
    }
    '/_authenticated/jogo/loja': {
      id: '/_authenticated/jogo/loja'
      path: '/loja'
      fullPath: '/jogo/loja'
      preLoaderRoute: typeof AuthenticatedJogoLojaRouteImport
      parentRoute: typeof AuthenticatedJogoRoute
    }
    '/_authenticated/jogo/inventario': {
      id: '/_authenticated/jogo/inventario'
      path: '/inventario'
      fullPath: '/jogo/inventario'
      preLoaderRoute: typeof AuthenticatedJogoInventarioRouteImport
      parentRoute: typeof AuthenticatedJogoRoute
    }
    '/_authenticated/jogo/equipe': {
      id: '/_authenticated/jogo/equipe'
      path: '/equipe'
      fullPath: '/jogo/equipe'
      preLoaderRoute: typeof AuthenticatedJogoEquipeRouteImport
      parentRoute: typeof AuthenticatedJogoRoute
    }
    '/_authenticated/jogo/combate': {
      id: '/_authenticated/jogo/combate'
      path: '/combate'
      fullPath: '/jogo/combate'
      preLoaderRoute: typeof AuthenticatedJogoCombateRouteImport
      parentRoute: typeof AuthenticatedJogoRoute
    }
  }
}

interface AuthenticatedJogoRouteChildren {
  AuthenticatedJogoCombateRoute: typeof AuthenticatedJogoCombateRoute
  AuthenticatedJogoEquipeRoute: typeof AuthenticatedJogoEquipeRoute
  AuthenticatedJogoInventarioRoute: typeof AuthenticatedJogoInventarioRoute
  AuthenticatedJogoLojaRoute: typeof AuthenticatedJogoLojaRoute
  AuthenticatedJogoMissoesRoute: typeof AuthenticatedJogoMissoesRoute
  AuthenticatedJogoPrioridadesRoute: typeof AuthenticatedJogoPrioridadesRoute
  AuthenticatedJogoSocialRoute: typeof AuthenticatedJogoSocialRoute
  AuthenticatedJogoIndexRoute: typeof AuthenticatedJogoIndexRoute
}

const AuthenticatedJogoRouteChildren: AuthenticatedJogoRouteChildren = {
  AuthenticatedJogoCombateRoute: AuthenticatedJogoCombateRoute,
  AuthenticatedJogoEquipeRoute: AuthenticatedJogoEquipeRoute,
  AuthenticatedJogoInventarioRoute: AuthenticatedJogoInventarioRoute,
  AuthenticatedJogoLojaRoute: AuthenticatedJogoLojaRoute,
  AuthenticatedJogoMissoesRoute: AuthenticatedJogoMissoesRoute,
  AuthenticatedJogoPrioridadesRoute: AuthenticatedJogoPrioridadesRoute,
  AuthenticatedJogoSocialRoute: AuthenticatedJogoSocialRoute,
  AuthenticatedJogoIndexRoute: AuthenticatedJogoIndexRoute,
}

const AuthenticatedJogoRouteWithChildren =
  AuthenticatedJogoRoute._addFileChildren(AuthenticatedJogoRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCriarHeroiRoute: typeof AuthenticatedCriarHeroiRoute
  AuthenticatedJogoRoute: typeof AuthenticatedJogoRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCriarHeroiRoute: AuthenticatedCriarHeroiRoute,
  AuthenticatedJogoRoute: AuthenticatedJogoRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ConfirmarEmailRoute: ConfirmarEmailRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RankingRoute: RankingRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
